<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "menu_item_addon".
 *
 * @property string $menu_item_id
 * @property string $addon_id
 *
 * @property Addons $addon
 * @property MenuItems $menuItem
 */
class MenuItemAddon extends \yii\db\ActiveRecord
{

    const SCENARIO_GET_DETAILS_BY_CLIENT = 'get_details_by_client';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_item_addon';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['menu_item_id', 'addon_id'], 'required'],
            [['menu_item_id', 'addon_id'], 'integer'],
            [['addon_id'], 'exist', 'skipOnError' => true, 'targetClass' => Addons::className(), 'targetAttribute' => ['addon_id' => 'id']],
            [['menu_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => MenuItems::className(), 'targetAttribute' => ['menu_item_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'menu_item_id' => 'Menu Item ID',
            'addon_id' => 'Addon ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddon()
    {
        return $this->hasOne(Addons::className(), ['id' => 'addon_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuItem()
    {
        return $this->hasOne(MenuItems::className(), ['id' => 'menu_item_id']);
    }

    /**
     * @inheritdoc
     * @return MenuItemAddonQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MenuItemAddonQuery(get_called_class());
    }
    
    public function afterValidate()
    {
        if ($this->hasErrors()) {
            return Helpers::HttpException(422,'validation failed', ['error' => $this->errors]);
        }
    }

    public function scenarios()
    {
        return ArrayHelper::merge(
            parent::scenarios(),
            [
                self::SCENARIO_GET_DETAILS_BY_CLIENT => [
                    'addon' => function() {
                        return $this->addon;
                    }
                ],
            ]);
    }

    public function fields()
    {
        $request_action = explode('/', Yii::$app->getRequest()->getUrl());
        if (in_array('clients', $request_action) && Yii::$app->request->isGet && isset(Yii::$app->request->get()['id'])) {
            return $this->scenarios()[self::SCENARIO_GET_DETAILS_BY_CLIENT];
        }
        return parent::fields(); // TODO: Change the autogenerated stub
    }
    
}
