<?php

namespace common\models;


use Yii;
use common\helpers\Helpers;

/**
 * This is the model class for table "reviews".
 *
 * @property string $id
 * @property string $rank
 * @property string $comment
 * @property string $restaurant_id
 * @property string $client_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $title
 *
 * @property Clients $client
 * @property Restaurants $restaurant
 */
class Reviews extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reviews';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rank', 'restaurant_id', 'title'], 'required'],
            [['rank'], 'number'],
            ['rank', 'compare', 'compareValue' => 1, 'operator' => '>='],
            ['rank', 'compare', 'compareValue' => 5, 'operator' => '<='],
            [['restaurant_id', 'client_id'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['comment', 'title'], 'string', 'max' => 255],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Clients::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['restaurant_id'], 'exist', 'skipOnError' => true, 'targetClass' => Restaurants::className(), 'targetAttribute' => ['restaurant_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rank' => 'Rank',
            'comment' => 'Comment',
            'restaurant_id' => 'Restaurant ID',
            'client_id' => 'Client ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurant()
    {
        return $this->hasOne(Restaurants::className(), ['id' => 'restaurant_id']);
    }

    /**
     * @inheritdoc
     * @return ReviewsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ReviewsQuery(get_called_class());
    }

    public static function getReviews()
    {
        $restaurant = Restaurants::checkRestaurantAccess();
        return Helpers::formatResponse(true, 'get success', $restaurant->reviews);
    }

    public function afterValidate()
    {
        if ($this->hasErrors()) {
            return Helpers::HttpException(422, 'validation failed', ['error' => $this->errors]);
        }
    }

    public function beforeSave($insert)
    {
        if (!$this->isNewRecord)
            $this->updated_at = date('Y-m-d H:i:s');
        else
            $this->created_at = date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function fields()
    {
        return [
            'id' => function () {
                return (int)$this->id;
            },
            'name' => function () {
                return (!empty($this->client) ? (string)$this->client->user->username : 'Unknown User');
            },
            'title' => function () {
                return (string)$this->title;
            },
            'comment' => function () {
                return (string)$this->comment;
            },
            'rank' => function () {
                return (float)$this->rank;
            },
            'created_at' => function () {
                return (string)$this->created_at;
            }
        ];
    }
}